### ISSUE TITLE
Error while running run.py

### ISSUE THREAD

**Issue by shubhampost4u** [a20r/locaudio#2]
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    locaudio.run(sys.argv[1], sys.argv[2], sys.argv[3])
IndexError: list index out of range

**Comment by severusbunny** [comment]
> Traceback (most recent call last):
> File "run.py", line 8, in
> locaudio.run(sys.argv[1], sys.argv[2], sys.argv[3])
> IndexError: list index out of range

have you figure it out? I have the same trouble like you
